name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Deps
      run: yarn
      env:
        CI: true
    - name: Testing/Coverage
      run: yarn coverage --color
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - if: contains(github.ref, 'tags') && matrix.node-version == '14.x'
      name: Building release package
      run: yarn build
    - if: contains(github.ref, 'tags') && matrix.node-version == '14.x'
      name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
        package: ./Release/package.json
